### ISSUE TITLE
In line 88 of ridge_filter.py : float can't be treated as integer

### ISSUE THREAD

**Issue by RastogiAbhijeet** [kjanko/python-fingerprint-recognition#1]
original code :
gabor_filter = np.array(np.zeros((180/angleInc,filt_rows,filt_cols)));

should be : 
gabor_filter = np.array(np.zeros((180//angleInc,filt_rows,filt_cols)));

**Comment by kingzley** [comment]
> original code :
> gabor_filter = np.array(np.zeros((180/angleInc,filt_rows,filt_cols)));
> 
> should be :
> gabor_filter = np.array(np.zeros((180//angleInc,filt_rows,filt_cols)));

Thanks alot RastogiAbhijeet.
Saved me lot of time.

**Comment by kjanko** [comment]
Could you submit a pull request with the change?
