### ISSUE TITLE
error shape

### ISSUE THREAD

**Issue by jacozsz** [kjanko/python-fingerprint-recognition#13]
i have the next error in terminal:

Traceback (most recent call last):
  File "app.py", line 109, in <module>
    main()
  File "app.py", line 77, in main
    kp1, des1 = get_descriptors(img1)
  File "app.py", line 45, in get_descriptors
    img = image_enhance.image_enhance(img)
  File "C:\Users\Jacozsz\Downloads\python-fingerprint-recognition-master\enhance\i
mage_enhance.py", line 15, in image_enhance
    normim,mask = ridge_segment(img,blksze,thresh);             # normalise the
image and find a ROI
  File "C:\Users\Jacozsz\Downloads\python-fingerprint-recognition-master\enhance\r
idge_segment.py", line 61, in ridge_segment
    rows,cols = im.shape;
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by smoothdvd** [comment]
same here

**Comment by ogabriel** [comment]
@jacozsz @smoothdvd have you both passed the arguments of the fingerprints?

I get the same error if i just pass something like `python app.py`

While it should be something like `python app.py <fingerprint_1> <fingerprint_2>`

**Comment by kostek443** [comment]
When i write the `python app.py <fingerprint_1> <fingerprint_2>` in comend of python I get this error.
`D:\python\python-fingerprint-recognition-master>python D:/python/python-fingerprint-recognition-master/app.py <101_1.tif> <101_2.tif>
< was unexpected at this time.
`
