### ISSUE TITLE
Are 101_2 and 102_2 from one person's fingerprint?

### ISSUE THREAD

**Issue by DingtianX** [kjanko/python-fingerprint-recognition#16]
![B{K6K`M{O)G)1IYU79IP7~O](https://user-images.githubusercontent.com/49474549/68301577-3679a100-00db-11ea-9d3a-2c58c9b45ba0.png)

The result shows that the "score/len(matches)" is 21 which is smaller than 33. But I dont think they are from one person's fingerprint.
Another question is how the threshold 33 is given?

**Comment by DingtianX** [comment]
![1](https://user-images.githubusercontent.com/49474549/68301847-cae40380-00db-11ea-8bf5-6a0a7341ae01.png)

**Comment by kjanko** [comment]
It's a placeholder value. The output returned by the algorithm is a distance metric. The threshold should be defined statistically depending on the results obtained from doing experiments on your data.
