### ISSUE TITLE
You should credit the authors from where you got the code

### ISSUE THREAD

**Issue by Utkarsh-Deshmukh** [kjanko/python-fingerprint-recognition#17]
Hi Kristijan Jankoski,
  I was looking at the enhance functions in your code and found that you have obtained the code from my repository https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python

![image](https://user-images.githubusercontent.com/13918778/68349361-c9054a80-00b1-11ea-9f54-999b08164b5b.png)

**I would really appreciate if you would either fork this from the original directory or cite the original repository in your documentation.**

**Comment by kjanko** [comment]
Your library is used in the original form and credit is maintained inside the files (as per BSD).

**Comment by kjanko** [comment]
FYI: I've added you inside the readme :)
