### ISSUE TITLE
Terminal input 

### ISSUE THREAD

**Issue by beyazitbirkan** [kjanko/python-fingerprint-recognition#2]
I am getting a error I think its related with input , how did you define your image selecting . I am trying in terminal  python3  --101_1.tif 
File "C:/Users/BBO/Desktop/python-fingerprint-recognition-master/app.py", line 44
    img = clahe.apply(img)
                         ^

**Comment by kjanko** [comment]
Hi,

please take a look at how the input is being read in the code. You need to provide two image paths as input parameters.
