### ISSUE TITLE
ModuleNotFoundError: No module named 'ridge_segment'

### ISSUE THREAD

**Issue by iamlohith** [kjanko/python-fingerprint-recognition#3]
![issue](https://user-images.githubusercontent.com/48597537/54443859-8a5c0200-4767-11e9-83f1-1913a013cb98.png)

huhfiew

please reply to this isssue

**Comment by renoojohn** [comment]
hi Lohithloli,

You can change the library imports in the image_enhance.py from 
from ridge_segment import ridge_segment
to 
**from . ridge_segment import ridge_segment** 

You can do the same for all the library imports in image_enhance.py file.

**Comment by sashuu6** [comment]
I have fixed all the error and given a pull request. You can checkout the forked repository in my profile.

**Comment by sashuu6** [comment]
I think we can close this issue.
